### ISSUE TITLE
Bot Intercepting Its Own Messages Multiple Times When It Shouldn't At All?

### ISSUE THREAD

**Issue by GalGreenfield** [campbellbrendene/discord-command-parser#17]
Hello,

I wrote code to check whether a user didn't add a command after the prefix, and message them if they do: https://pastebin.com/k2Mevri7

A small, an unrelated problem: when I send just the prefix (currently configured to be `$ `), when `message.content == prefix.trim()` AND when `prefix != prefix.trim()` (which is my case), `parsing_result.message.error` has a value about the message not starting with the prefix -  it shouldn't behave like that - does the library's `parse` function automatically `trim()`ing `message.content`? If that's the case, if the prefix ends with a whitespace, `parsing_result.message.content` will never be equal to the prefix. Edit: I know that I can set in the `parse` options `allowSpaceBeforeCommand: true` - but it still shouldn't behave like that.

And to the main issue:
When I evaluate the condition
```
if ( parsing_result.message.content == prefix.trim() ) {
    message.reply("Whoops, you forgot to add a command. Please give me a command.");
}
```

My bot sends *3* (update: 5, sometimes 4) messages, and when I log them inside that condition, they go through! Why is that happening? Their `message.content` can't literally be equal to `prefix.trim()`, since the messages the bot send literally starts with tagging me (the user whose message it's replying to), so I don't understand how it's possible.

**Comment by campbellbrendene** [comment]
Hi,

The `parse` function does not trim the prefix nor the message content when checking prefixes. The parse function uses `message.content.startsWith(prefix)` to determine whether the message matches the prefix. Therefore, if your prefix is `"$ "`, this will never be true for a message containing `"$"` since Discord disallows trailing whitespace in messages. Additionally, the `parse` function also does not mutate `message` nor `message.content` in any way.

Take this code for example:

```ts
const prefix = "$ ";

client.on("message", async message => {
  const parsed = parser.parse(message, prefix, { ignorePrefixCase: true, allowSpaceBeforeCommand: true });

  if (!message.author.bot && message.content === prefix.trim())
    await message.reply("Whoops, you forgot to add a command.");
});
```

This should work in the following ways:

if `message.content` = `"$"`:
- if statement gets triggered

if `message.content` = `"$ ping"`:
- parser succeeds; if statement does not trigger

if `message.content` = `"$  ping"`:
- parser succeeds (because of `allowSpaceBeforeCommand`); if statement does not trigger

if `message.content` = `"$ping"`:
- parser does not succeed, because it was searching for the exact prefix (`"$ "`) at the start of the string and did not find it; if statement does not trigger


> My bot sends 3 (update: 5, sometimes 4) messages, and when I log them inside that condition, they go through! Why is that happening? Their message.content can't literally be equal to prefix.trim(), since the messages the bot send literally starts with tagging me (the user whose message it's replying to), so I don't understand how it's possible.

This might be an issue with you running multiple instances of your bot in the background, or it could be an issue depending on your prefix. Try using the if statement in the example above which checks to make sure the author is not a bot account. This should prevent the bot from triggering itself accidentally. It's also a good idea to put a check like `if (message.author.bot) return` at the beginning of your message handler instead. Also as a side-note, `parse` already checks for bot users unless `allowBots: true` is in your options.

**Comment by GalGreenfield** [comment]
Thanks for the detailed information and quick response, it's much appreciated. :)
A day or so after I posted the issue, the bot stopped responding to its own messages (as it should), so I'm not sure what caused it. If the problem returns, I'll investigate and reply here.
For now, I'm closing the issue.
